# site properties and page defaults
title: physycom
subtitle: 
description: The City Science Laboratory is a multidisciplinary research group within the Department of Physics and
Astronomy at the University of Bologna. The Laboratory leverages expertise in physics, mathematics, and
computer science to explore and understand the complexity of urban systems. With a focus on mobility, climate,
and energy, the Laboratory aims to contribute to the development of sustainable and resilient cities by advancing
scientific methodologies and computational tools. The Laboratory collaborates closely with CINECA, one of the
largest high-performance computing centers in Europe, on several urban Digital Twin initiatives. A notable
example is the Digital Twin of the City of Bologna, which integrates diverse datasets and advanced modeling
techniques to provide actionable insights for urban planning, climate adaptation, and energy efficiency. The
Laboratory offers the expertise in the fields, Urban LiDAR and Orthophoto Analysis, Infrastructure Morphology
and Indicators, Vegetation and Climate Vulnerability Indices, Building Energy Simulations, Urban Microclimate
Simulations, Vehicular Mobility Modeling, Pedestrian Dynamics and Crowd Analysis. The City Science
Laboratory combines advanced computational methods with real-world applications, fostering collaborations with
stakeholders to address critical urban challenges and promote evidence-based decision-making.
header: images/background.jpg
footer: images/background.jpg
proofer: false

# site social media and other links
links:
  email: contact@physycom.com
  orcid: 0000-0001-8713-9213
  google-scholar: ETJoidYAAAAJ
  github: physycom
  twitter: physycom
  youtube: physycom

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
